version: "3.7"
services:
  tunnel:
    build:
      context: .
      args:
        USE_HTPASSWD: ${USE_HTPASSWD-true}

    container_name: tunnel

    restart: always

    ports:
      - "${SSH_PORT-3214}:22"
      - 80

    environment:
      VIRTUAL_HOST: ${HOST?Missing environment variable see doku}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${HOST:?Missing environment variable see readme}

    networks:
      - default
      - nginxproxynet

    volumes:
      - tunnelData:/etc/ssh

volumes:
  tunnelData:
    driver: local

networks:
  nginxproxynet:
    name: ${PROXY_NETWORK_NAME-nginxproxynet}
    external: true
